name: controllable_generator
description: A generator for the controllable and controllable_flutter packages that makes working with controllable easier.
version: 0.0.3
homepage: https://github.com/nivisi/controllable/tree/develop/packages/controllable_generator
repository: https://github.com/nivisi/controllable/tree/develop/packages/controllable_generator
issue_tracker: https://github.com/nivisi/controllable/labels/controllable_generator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^4.0.0
  build: ^2.3.0
  controllable: ^0.0.1+2
  dart_code_writer: ^0.0.7
  glob: ^2.0.1
  source_gen: ^1.2.2

dev_dependencies:
  build_runner: ^2.1.10
  build_test: ^2.1.5
  flutter_lints: ^1.0.0
