name: controllable_example
description: A simple Flutter project showing how to use controllable package.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  controllable_flutter:
    path: ../packages/controllable_flutter
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.10
  controllable_generator:
    path: ../packages/controllable_generator
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
