name: controllable
description: The core package of the controllable ecosystem that contains base classes and interfaces.
version: 0.0.4
environment:
  sdk: '>=2.12.0 <3.0.0'
repository: https://github.com/nivisi/controllable/tree/develop/packages/controllable
homepage: https://github.com/nivisi/controllable/tree/develop/packages/controllable
issue_tracker: https://github.com/nivisi/controllable/labels/controllable

dependencies:
  meta: ^1.0.0
  interfaces: ^0.0.4
dev_dependencies:
  lints: ^1.0.0
