name: controllable_flutter
description: The Flutter part of the controllable ecosystem that contains widgets to operate with the controllable on the UI level.
version: 0.0.1+1
homepage: https://github.com/nivisi/controllable/tree/develop/packages/controllable_flutter
repository: https://github.com/nivisi/controllable/tree/develop/packages/controllable_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  controllable: ^0.0.1+2
  flutter:
    sdk: flutter
  provider: ^6.0.2

dev_dependencies:
  flutter_lints: ^1.0.0

flutter: null